# Generated by Django 3.1.2 on 2021-07-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_page', '0002_auto_20210711_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
