# Generated by Django 3.0.3 on 2020-02-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.CharField(default='github.com/eiire', max_length=100),
            preserve_default=False,
        ),
    ]
