# Generated by Django 3.0.3 on 2020-03-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name_for_portfolios',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
    ]
